service: suicides-app

frameworkVersion: '3'

custom:
  datalakeBucket: ds4a-co6-t107-datalake

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: arn:aws:s3:::${self:custom.datalakeBucket}/*
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject

package:
  patterns:
  - '!**'
  individually: true

layers:
  pandas:
    path: src/libs/pandas
    package:
      patterns: 
        - "**/**"
    description: "Includes pandas and pyarrow"

functions:
  parquetize:
    handler: src/parquetize.handler
    timeout: 900 # 15 min, max timeout
    package:
      patterns:
        - src/parquetize.py
    layers:
      - !Ref PandasLambdaLayer
    events:
      - s3:
          bucket: ${self:custom.datalakeBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: cleaned/
            - suffix: .csv
